-- =====================================================================
-- SIRASA — Perbaikan: riwayat_kuis.id tidak punya nilai otomatis
-- Gejala: "null value in column "id" of relation "riwayat_kuis" violates
-- not-null constraint" saat mengirim kuis / menyimpan durasi baca, sehingga
-- tidak ada riwayat yang tersimpan (waktu belajar, progres, tes = 0).
-- =====================================================================
alter table public.riwayat_kuis alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.riwayat_kuis', 'id'),
              coalesce((select max(id) from public.riwayat_kuis), 0) + 1, false);
