-- =====================================================================
-- Macaya — Kamus ejaan suara (TTS)
-- Singkatan/kata yang harus dibaca dengan cara tertentu, mis. HIV -> "ha i ve".
-- Dipakai Edge Function tts-slide (suara neural) dan suara perangkat di browser.
-- Kata dicocokkan utuh & peka huruf besar (HIV ≠ hiv). Aman dijalankan berulang.
-- =====================================================================

create table if not exists public.kamus_ucapan (
    id         bigint generated by default as identity primary key,
    kata       text not null unique,      -- tulisan di materi, mis. HIV
    ucapan     text not null,             -- cara dibaca, mis. ha i ve
    created_at timestamptz not null default now()
);

alter table public.kamus_ucapan enable row level security;
drop policy if exists "kamus_baca"  on public.kamus_ucapan;
drop policy if exists "kamus_admin" on public.kamus_ucapan;
create policy "kamus_baca"  on public.kamus_ucapan for select to anon, authenticated using (true);
create policy "kamus_admin" on public.kamus_ucapan for all    to authenticated
    using (public.is_admin()) with check (public.is_admin());

insert into public.kamus_ucapan (kata, ucapan) values
    ('HIV',   'ha i ve'),
    ('AIDS',  'eids'),
    ('ARV',   'a er ve'),
    ('ODHIV', 'o de ha i ve'),
    ('ODHA',  'od ha'),
    ('WHO',   'we ha o'),
    ('ASI',   'a es i'),
    ('IMS',   'i em es'),
    ('RI',    'er i')
on conflict (kata) do nothing;
